spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/lotto-web

lotto:
  number-generator:
    lotteryRunOccurrence: "0 0 12 * * 6"
    facade:
      lowerBand: 1
      upperBand: 99
      count: 6
    http:
      client:
        config:
          uri: http://www.randomnumberapi.com
          port: 80
          connectionTimeout: 1000
          readTimeout: 1000
