spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: mongodb://${MONGO_USER}:${MONGO_PASSWORD}@${MONGO_HOST}:${MONGO_PORT}/${MONGO_DB_NAME}?authSource=${MONGO_AUTH_SOURCE}
      auto-index-creation: true
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

lotto:
  number-generator:
    lotteryRunOccurrence: "0 55 11 * * 6"
    facade:
      lowerBand: 1
      upperBand: 99
      count: 14
    http:
      client:
        config:
          uri: http://ec2-3-120-147-150.eu-central-1.compute.amazonaws.com
          port: 9090
          connectionTimeout: 1000
          readTimeout: 1000
  result-checker:
    generateResultsRunOccurrence: "0 0 12 * * 6"

server:
  port: 8000