spring:
  main:
    allow-bean-definition-overriding: true
  data:
    mongodb:
      uri: mongodb://admin:admin@localhost:27017/lotto-web
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

lotto:
  number-generator:
    lotteryRunOccurrence: "0 55 11 * * 6"
    facade:
      lowerBand: 1
      upperBand: 99
      count: 14
    http:
      client:
        config:
          uri: http://www.randomnumberapi.com
          port: 80
          connectionTimeout: 1000
          readTimeout: 1000
  result-checker:
    generateResultsRunOccurrence: "0 0 12 * * 6"